In [1]:
file=open("puzzle.txt","r")

In [2]:
puzzle=file.read()

In [3]:
print(puzzle)

705600103001070900032001740000890061200000004510034000083700590009050600607002408


In [4]:
import numpy as np

In [5]:
original=np.zeros((9,9))
for i in range(9):
    for j in range(9):
        original[i][j]=puzzle[i*9+j]
        
original=original.astype(int)
print(original)

[[7 0 5 6 0 0 1 0 3]
 [0 0 1 0 7 0 9 0 0]
 [0 3 2 0 0 1 7 4 0]
 [0 0 0 8 9 0 0 6 1]
 [2 0 0 0 0 0 0 0 4]
 [5 1 0 0 3 4 0 0 0]
 [0 8 3 7 0 0 5 9 0]
 [0 0 9 0 5 0 6 0 0]
 [6 0 7 0 0 2 4 0 8]]


In [6]:
def selectRow(row,matrix):
    for i in range (324):
    #for i in range (81):
        if matrix[row][i]==1:
            for j in range (729):
                if matrix[j][i]==1 and j!=row:
                    matrix[j]=0
    return matrix
#for k in range (9): for j in range (9): m=int(original[k][j]) if m>0: exactcover[:,j+9k]=0 exactcover[k80+j9+m-1][j+9k]=1

In [7]:
def showMatrix(matrix):
    f=open("exactcover.txt","w+")
    for i in range(729):
        for j in range(324):
            test=np.array2string(matrix[i][j])
            f.write(test)
        f.write("\n")

In [8]:
def showPuzzle(ones,matrix):
    puzzle=np.zeros((9,9))
    for i in range (81):
        if ones[i]==1:
            for j in range (729):
                if matrix[j][i]==1:
                    puzzleRow=int(j/81)
                    puzzleColumn=i%9
                    num=(j%9+1)
                    puzzle[puzzleRow][puzzleColumn]=num
    return puzzle
                    #print(num)
                

In [9]:
def ones(matrix):
    ones=np.zeros(324)
    for a in range (324):
        count=0
        for b in range (729):
            if matrix[b][a]==1:
                count+=1
        ones[a]=count
    return ones

In [10]:
#Initial set up for specific puzzle
def setup(puzzle):
    exactcover=np.zeros((729,324))
    exactcover=exactcover.astype(int)

    for i in range (81):
        for j in range (9):
            exactcover[j+i*9][i]=1

    for n in range (9): 
        for m in range (9):
            for k in range (9):  
                exactcover[k+m*9+81*n][81+k+9*n]=1
                exactcover[k+m*9+81*n][162+k+9*m]=1

    for p in range (3):
        for q in range (3):
            for n in range (3):
                for m in range (3):
                    for k in range (9):  
                        exactcover[k+m*9+27*n+81*q+243*p][243+k+9*n+27*p]=1

    for k in range (9):
        for j in range (9):
            m=int(puzzle[k][j])
            if m>0:
                row=k*81+j*9+m-1
                exactcover=selectRow(row,exactcover)
    return exactcover

In [11]:
exactcover=setup(original)

In [12]:
showMatrix(exactcover)

In [14]:
initialone=ones(exactcover)
#print(initialone)

In [15]:
working=showPuzzle(initialone, exactcover)
#print(working)

In [16]:
#experiment
def update(columncount, matrix, count, trial):
    originalmatrix=matrix
    newone=np.zeros(324)
    for a in range (324):
        if columncount[a]==count:
            for b in range (729):
                if trial==1:
                    if matrix[b][a]==1:
                        selectRow(b,matrix)
                elif trial==2:
                    for c in range (b,729):
                        selectRow(c,matrix)
                if count>1:
                    count=1
    
    previousone=newone                   
    newone=ones(matrix)
    if np.all(newone)==0:
        print("fail")
        return newone
        if trial==2:
            return "abort"
        #print(newone)
        newone=update(previousone,matrix,2,2)
        #return newone
    check=1
    change=columncount[0:80]-newone[0:80]
    checkones=np.ones(80)
    finished=newone[0:80]-checkones
    if np.any(change):
        print("change")
        check=1
        newone=update(newone,matrix,check,1)
    elif not(np.any(finished)):
        print("done")
    else:
        check+=1
        if check>9:
            return "abort"
        update(newone,matrix,check,1)
    #print("check="+str(check))
    #print (newone)
    return newone   

In [17]:
testone=update(initialone,exactcover, 1,1)
#testone

change
change
done


In [18]:
working=showPuzzle(testone, exactcover)
print(working)

[[7. 4. 5. 6. 2. 9. 1. 8. 3.]
 [8. 6. 1. 4. 7. 3. 9. 2. 5.]
 [9. 3. 2. 5. 8. 1. 7. 4. 6.]
 [3. 7. 4. 8. 9. 5. 2. 6. 1.]
 [2. 9. 8. 1. 6. 7. 3. 5. 4.]
 [5. 1. 6. 2. 3. 4. 8. 7. 9.]
 [1. 8. 3. 7. 4. 6. 5. 9. 2.]
 [4. 2. 9. 3. 5. 8. 6. 1. 7.]
 [6. 5. 7. 9. 1. 2. 4. 3. 8.]]
